<?php
/**
 * @file
 * Page callbacks for the OpenBeerFest core pages.
 */

/**
 * Page callback for /blog
 */
function openbeerfest_core_blog() {
  return theme('openbeerfest_core_blog', array());
}

/**
 * Page callback for /breweries
 */
function openbeerfest_core_breweries() {
  return theme('openbeerfest_core_breweries', array());
}

/**
 * Page callback for /music
 */
function openbeerfest_core_music() {
  return theme('openbeerfest_core_music', array());
}

/**
 * Page callback for /food
 */
function openbeerfest_core_food() {
  return theme('openbeerfest_core_food', array());
}

/**
 * Page callback for /seminars
 */
function openbeerfest_core_seminars() {
  return theme('openbeerfest_core_seminars', array());
}

/**
 * Page callback for /sponsors
 */
function openbeerfest_core_sponsors() {
  return theme('openbeerfest_core_sponsors', array());
}

/**
 * Page callback for /contact
 */
function openbeerfest_core_contact() {
  return theme('openbeerfest_core_contact', array());
}
